### ISSUE TITLE
Library need to conform to spring starter style libraries

### ISSUE THREAD

**Issue by Mjwillis** [ministryofjustice/hmpps-digital-prison-reporting-lib#119] opened 2024-03-15 14:37 UTC
Currently this library has been built in a way that makes other applications that use it have to add additional scans to the classpath. 

This is not necessary. There is a pattern to building these libraries that this should following, such an example is https://github.com/ministryofjustice/hmpps-kotlin-lib the Kotlin Helper library for HMPPS applications or https://github.com/ministryofjustice/hmpps-spring-boot-sqs for SQS

These libraries are a light touch and make use of **autoconfigure** patterns e.g. https://github.com/ministryofjustice/hmpps-spring-boot-sqs/tree/main/hmpps-sqs-spring-boot-autoconfigure 

Currently due to forcing to add additional component scans - tests are failing on services (i.e. issue https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/issues/108) 

Please could we adopt the standard HMPPS pattern like the above for this project.

**Comment by gavriil-g-moj** [comment] 2024-03-15 16:04
The following Jira task has been created to investigate this issue:
https://dsdmoj.atlassian.net/browse/DPR2-503

**Comment by gavriil-g-moj** [comment] 2024-03-20 16:18
@Mjwillis the requested changed have been made in the following PR:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/pull/121

**Comment by xoen** [comment] 2024-03-20 16:47
This is in version `3.6.0` right? I just gave it a try locally and the application starts when I upgrade the dependency version and remove the `@ComponentScan` annotation:

```
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -21,7 +21,7 @@ dependencies {
   implementation("org.springframework.boot:spring-boot-starter-validation")

   implementation("uk.gov.justice.service.hmpps:hmpps-sqs-spring-boot-starter:3.1.1")
-  implementation("uk.gov.justice.service.hmpps:hmpps-digital-prison-reporting-lib:3.5.2")
+  implementation("uk.gov.justice.service.hmpps:hmpps-digital-prison-reporting-lib:3.6.0")

   implementation("io.opentelemetry:opentelemetry-api:1.36.0")
   implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.2.0")
diff --git a/src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/HmppsNonAssociationsApi.kt b/src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/HmppsNonAssociationsApi.kt
index 99e8ceb..cd709d8 100644
--- a/src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/HmppsNonAssociationsApi.kt
+++ b/src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/HmppsNonAssociationsApi.kt
@@ -10,10 +10,6 @@ import org.springframework.context.annotation.ComponentScan
 const val SYSTEM_USERNAME = "NON_ASSOCIATIONS_API"

 @SpringBootApplication()
-@ComponentScan(
-  "uk.gov.justice.digital.hmpps.hmppsnonassociationsapi",
-  "uk.gov.justice.digital.hmpps.digitalprisonreportinglib",
-)
```

**However** I no longer see the DPR endpoints in Swagger and the UI gets a 404 when trying to get the report. **The endpoints don't seem to be automatically registered anymore**:

```
2024-03-20 16:42:30.821 DEBUG 75121 --- [nio-8080-exec-7] ssociationsApiExceptionHandler$Companion : No resource found exception caught: No static resource definitions/non-associations/all. | userId=[...]
```

PS: Thanks again for looking into this ☺️

**Comment by gavriil-g-moj** [comment] 2024-03-21 09:46
For reference, this is the PR removing the component scan from our hosting application:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-mi/pull/148/files

**Comment by xoen** [comment] 2024-03-22 09:21
Hi @gavriil-g-moj thanks for your replies, how odd. Yes, this is pretty much how the changes on how side looks like: https://github.com/ministryofjustice/hmpps-non-associations-api/pull/240/commits/ab99b4e898401736de968e42fe3272131bf80a38

I'll play with it a bit more later and see if I missed something. I'll keep you posted.

**Comment by xoen** [comment] 2024-03-26 10:41
Hi @gavriil-g-moj those PRs are now in `dev` and I can confirm library now works without requiring the `@ComponentScan`, thanks again for making the library so much easier to use.

I'll leave the honour to close this one to you ☺️

**Comment by gavriil-g-moj** [comment] 2024-03-26 11:21
That's great, thanks for testing this Aldo and helping to improve the library.

**Closed by gavriil-g-moj** 2024-03-26 11:21 UTC
